// AUTO-GENERADO desde data/coldrone_seed_v0.4 por scripts/gen_incidents.py
// No editar a mano.

export type Incident = {
  id: string;
  date: string;
  departamento: string;
  municipio: string;
  lat: number;
  lon: number;
  perpetrator: string;
  status: string;
  method: string;
  target: string;
  fatalities: number;
  injuries: number;
  civKilled: number;
  milKilled: number;
  notes: string;
};

export const incidents: Incident[] = [
  {
    "id": "COL-2018-001",
    "date": "6/1/2018",
    "departamento": "Guainia",
    "municipio": "Barranco Minas",
    "lat": 3.5,
    "lon": -69.81,
    "perpetrator": "grupo armado (s/d)",
    "status": "attack_failed",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "explosivo no detono"
  },
  {
    "id": "COL-2019-002",
    "date": "9/1/2019",
    "departamento": "Narino",
    "municipio": "(s/d)",
    "lat": 1.5,
    "lon": -77.87,
    "perpetrator": "grupo armado (s/d)",
    "status": "interdiction_seizure",
    "method": "interdiction_seizure",
    "target": "na",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "hallazgo: 2 drones Syma"
  },
  {
    "id": "COL-2021-003",
    "date": "10/22/2021",
    "departamento": "Meta",
    "municipio": "La Macarena",
    "lat": 2.03,
    "lon": -74.14,
    "perpetrator": "EMC (estructura Jaime Martinez)",
    "status": "attack",
    "method": "kinetic_firing",
    "target": "military",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "Disparo hacía base"
  },
  {
    "id": "COL-2023-004",
    "date": "7/22/2023",
    "departamento": "Putumayo",
    "municipio": "Puerto Guzmán",
    "lat": 0.4,
    "lon": -77.0,
    "perpetrator": "grupo armado (s/d)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "el dron fue “ubicado por el puesto de observación, que logra identificar que llevaba un objeto. El objeto es soltado y al momento de caer explota, a unos 400 metros (de) donde se encontraba el puesto avanzado”."
  },
  {
    "id": "COL-2024-005",
    "date": "4/26/2024",
    "departamento": "Cauca",
    "municipio": "Argelia",
    "lat": 2.26,
    "lon": -77.25,
    "perpetrator": "EMC (frente Carlos Patino)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "na",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "PRIMER ataque del registro de 418"
  },
  {
    "id": "COL-2024-006",
    "date": "2024-10_a_2025-05",
    "departamento": "Cauca",
    "municipio": "Argelia",
    "lat": 2.26,
    "lon": -77.0,
    "perpetrator": "EMC",
    "status": "aggregate",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 5,
    "injuries": 10,
    "civKilled": 0,
    "milKilled": 5,
    "notes": "Entre octubre de 2024 y mayo de 2025, durante la Operación Perseo, las Fuerzas Militares enfrentaron 183 ataques de dron en el corregimiento El Plateado de Argelia (Cauca)"
  },
  {
    "id": "COL-2025-007",
    "date": "2/17/2025",
    "departamento": "Cauca",
    "municipio": "Argelia",
    "lat": 2.26,
    "lon": -77.0,
    "perpetrator": "EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "GRANADA sobre hospital de campana de Medicos Sin Fronteras; trabajador de salud herido"
  },
  {
    "id": "COL-2025-008",
    "date": "2/18/2025",
    "departamento": "Cauca",
    "municipio": "Argelia",
    "lat": 2.26,
    "lon": -77.0,
    "perpetrator": "EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 2,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "3 drones lanzaron granadas artesanales; 2 habitantes heridos + danos a viviendas"
  },
  {
    "id": "COL-2025-009",
    "date": "2/24/2025",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "grupo armado (s/d: ELN o EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 0,
    "injuries": 1,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "soldado profesional herido, evacuado a Cucuta"
  },
  {
    "id": "COL-2025-010",
    "date": "3/3/2025",
    "departamento": "Norte de Santander",
    "municipio": "Teorama",
    "lat": 8.43,
    "lon": -73.29,
    "perpetrator": "ELN (Frente Héctor)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 1,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 1,
    "notes": "soldado profesional asesinado"
  },
  {
    "id": "COL-2025-011",
    "date": "3/26/2025",
    "departamento": "Cauca",
    "municipio": "Suarez",
    "lat": 2.96,
    "lon": -76.7,
    "perpetrator": "EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 2,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "explosivos contra Policia impactaron cerca del hospital local; varios civiles heridos por onda expansiva"
  },
  {
    "id": "COL-2025-012",
    "date": "3/27/2025",
    "departamento": "Norte de Santander",
    "municipio": "El Tarra",
    "lat": 8.58,
    "lon": -73.1,
    "perpetrator": "crossfire ELN / Frente 33",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 1,
    "injuries": 0,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "Luis Ernesto Mendoza (73 anos): perdio un brazo y murio dias despues"
  },
  {
    "id": "COL-2025-013",
    "date": "4/5/2025",
    "departamento": "Norte de Santander",
    "municipio": "El Tarra",
    "lat": 8.58,
    "lon": -73.1,
    "perpetrator": "crossfire ELN / Frente 33",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 1,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "mujer de 44 anos herida en el cuello cerca de su vivienda"
  },
  {
    "id": "COL-2025-014",
    "date": "4/16/2025",
    "departamento": "Cauca",
    "municipio": "Santander de Quilichao",
    "lat": 3.01,
    "lon": -76.48,
    "perpetrator": "EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 1,
    "injuries": 2,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "Un trabajador de una compañía de energía eléctrica murió y su compañero resultó herido en un ataque con explosivos lanzados desde un dron"
  },
  {
    "id": "COL-2025-015",
    "date": "5/16/2025",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "EMC (escuela Filo Gringo)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 1,
    "injuries": 12,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "Luis Antonio (12 anos) muerto; madre Marli Aragon Vaca herida; granada de mortero rompio techo"
  },
  {
    "id": "COL-2025-016",
    "date": "5/23/2025",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "EMC (escuela Filo Gringo)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "viviendas de madera destruidas"
  },
  {
    "id": "COL-2025-017",
    "date": "7/11/2025",
    "departamento": "Cauca",
    "municipio": "Santander de Quilichao",
    "lat": 3.01,
    "lon": -76.48,
    "perpetrator": "EMC (frente Jaime Martínez)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 2,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 2,
    "notes": "patrullera Maryuri Ramos Mamian MUERTA en la estacion de Policia local"
  },
  {
    "id": "COL-2025-018",
    "date": "8/21/2025",
    "departamento": "Antioquia",
    "municipio": "Amalfi",
    "lat": 6.91,
    "lon": -75.08,
    "perpetrator": "EMC frente 36 (alias Calarca)",
    "status": "attack",
    "method": "kamikaze_fpv",
    "target": "military",
    "fatalities": 13,
    "injuries": 4,
    "civKilled": 0,
    "milKilled": 13,
    "notes": "derribo helicoptero Black Hawk; cifra 6->8->12->13"
  },
  {
    "id": "COL-2025-019",
    "date": "8/31/2025",
    "departamento": "Cauca",
    "municipio": "Patia",
    "lat": 2.12,
    "lon": -76.99,
    "perpetrator": "EMC (frente Carlos Patino / Jaime Martinez)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 0,
    "injuries": 3,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "ataque a estacion de Policia de El Bordo; 3 policias heridos; otro vehiculo-bomba no detono frente a la base"
  },
  {
    "id": "COL-2025-020",
    "date": "9/2/2025",
    "departamento": "Cauca",
    "municipio": "Patia",
    "lat": 2.12,
    "lon": -76.99,
    "perpetrator": "EMC (Mordisco)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 1,
    "injuries": 3,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "dron + motobomba; 1 civil + suboficial y 2 soldados heridos (Operacion Perseo II)"
  },
  {
    "id": "COL-2025-021",
    "date": "10/2/2025",
    "departamento": "Cauca",
    "municipio": "Patia",
    "lat": 2.12,
    "lon": -76.99,
    "perpetrator": "EMC (Mordisco)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 0,
    "injuries": 4,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "2 ataques casi simultaneos; explosivo cerca de estacion de Policia (Alcaldia, Banco Agrario, Palacio Justicia); 4 heridos civiles y funcionarios"
  },
  {
    "id": "COL-2025-022",
    "date": "10/10/2025",
    "departamento": "Bolivar",
    "municipio": "(sur de Bolivar)",
    "lat": 8.0,
    "lon": -74.0,
    "perpetrator": "EMC vs Clan del Golfo",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "enfrentamiento disidencias vs Clan del Golfo"
  },
  {
    "id": "COL-2025-023",
    "date": "10/14/2025",
    "departamento": "Guaviare",
    "municipio": "Calamar",
    "lat": 1.96,
    "lon": -72.65,
    "perpetrator": "EMC (estructura Armando Rios)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 0,
    "injuries": 4,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "ataque coordinado: casa del alcalde Farid Camilo Castano (empleada herida, mascotas muertas), estacion Policia y Batallon Selva 24 (1 soldado herido); 1 dron derribado"
  },
  {
    "id": "COL-2025-024",
    "date": "10/20/2025",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "crossfire ELN / Frente 33",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 1,
    "injuries": 1,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "adulto mayor asesinado; mujer acompanante herida (a hospital de Ocana)"
  },
  {
    "id": "COL-2025-025",
    "date": "11/12/2025",
    "departamento": "Narino",
    "municipio": "El Peñol",
    "lat": 1.45,
    "lon": -77.45,
    "perpetrator": "EMC",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 0,
    "injuries": 2,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "explosivos desde drones contra estacion de Policia; 2 uniformados heridos"
  },
  {
    "id": "COL-2025-026",
    "date": "12/18/2025",
    "departamento": "Cesar",
    "municipio": "Aguachica",
    "lat": 8.31,
    "lon": -73.61,
    "perpetrator": "ELN",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "mixed",
    "fatalities": 7,
    "injuries": 30,
    "civKilled": 0,
    "milKilled": 7,
    "notes": "ataque a base militar; KCH 6/31 vs Guardian/QZ 7/30"
  },
  {
    "id": "COL-2026-027",
    "date": "1/14/2026",
    "departamento": "Choco",
    "municipio": "San José del Palmar",
    "lat": 5.75,
    "lon": -76.25,
    "perpetrator": "ELN (frente Ernesto Che Guevara)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 0,
    "injuries": 10,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "dron con IED contra patrulla del Batot N.25 (XV Brigada); 9 soldados + 1 suboficial heridos por esquirlas"
  },
  {
    "id": "COL-2026-028",
    "date": "2/1/2026",
    "departamento": "Antioquia",
    "municipio": "Segovia",
    "lat": 7.08,
    "lon": -74.7,
    "perpetrator": "grupo armado (s/d)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 3,
    "injuries": 0,
    "civKilled": 3,
    "milKilled": 0,
    "notes": "proyectil de mortero sobre vivienda: madre y sus 2 hijos muertos"
  },
  {
    "id": "COL-2026-029",
    "date": "2/17/2026",
    "departamento": "Arauca",
    "municipio": "Saravena",
    "lat": 7.09,
    "lon": -70.76,
    "perpetrator": "ELN",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "infrastructure",
    "fatalities": 0,
    "injuries": 1,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "base de la Fuerza Aeroespacial Colombiana atacada con drones tipo FPV"
  },
  {
    "id": "COL-2026-030",
    "date": "2/22/2026",
    "departamento": "Cauca",
    "municipio": "Guachene",
    "lat": 3.13,
    "lon": -76.39,
    "perpetrator": "EMC (estructura Jaime Martinez)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "PRIMER ataque registrado de 2026 (entre Jamundi y norte del Cauca)"
  },
  {
    "id": "COL-2026-031",
    "date": "3/12/2026",
    "departamento": "Norte de Santander",
    "municipio": "El Tarra",
    "lat": 8.58,
    "lon": -73.1,
    "perpetrator": "grupo armado (s/d)",
    "status": "threat_psyops",
    "method": "psyops_megaphone",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "desplazamiento forzado 84 personas (33 menores)"
  },
  {
    "id": "COL-2026-032",
    "date": "4/6/2026",
    "departamento": "Norte de Santander",
    "municipio": "El Tarra",
    "lat": 8.58,
    "lon": -73.1,
    "perpetrator": "crossfire Frente 33 / ELN",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 1,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "explosivos cerca de viviendas; incendio en una casa; mujer 44 anos herida (reportes)"
  },
  {
    "id": "COL-2026-033",
    "date": "4/20/2026",
    "departamento": "Nariño",
    "municipio": "Ipiales",
    "lat": 0.83,
    "lon": -77.64,
    "perpetrator": "Comandos de Frontera (CNEB)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 3,
    "injuries": 2,
    "civKilled": 0,
    "milKilled": 3,
    "notes": "3 soldados profesionales muertos; Grupo de Caballeria Mediano N.3"
  },
  {
    "id": "COL-2026-034",
    "date": "4/27/2026",
    "departamento": "Norte de Santander",
    "municipio": "(Tibu/El Tarra/Sardinata)",
    "lat": 8.5,
    "lon": -72.9,
    "perpetrator": "crossfire ELN / Frente 33",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "~5 viviendas dañadas (ventanas, puertas, paredes); sin heridos"
  },
  {
    "id": "COL-2026-035",
    "date": "5/1/2026",
    "departamento": "Cundinamarca",
    "municipio": "Bogota",
    "lat": 4.7,
    "lon": -74.15,
    "perpetrator": "grupo armado (s/d)",
    "status": "interdiction_seizure",
    "method": "interdiction_seizure",
    "target": "na",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "dron cargado de explosivos hallado cerca del aeropuerto El Dorado y base militar adyacente"
  },
  {
    "id": "COL-2026-036",
    "date": "5/14/2026",
    "departamento": "Multiples (Cauca/Arauca/Boyaca/Caqueta/Casanare)",
    "municipio": "",
    "lat": 2.46,
    "lon": -76.8,
    "perpetrator": "EMC (red alias Dron)",
    "status": "enforcement",
    "method": "na",
    "target": "na",
    "fatalities": 0,
    "injuries": 0,
    "civKilled": 0,
    "milKilled": 0,
    "notes": "captura red de suministro, incluyendo 3 drones modificados; 5 personas capturadas incluido alias dron"
  },
  {
    "id": "COL-2026-037",
    "date": "5/19/2026",
    "departamento": "Cauca",
    "municipio": "Suarez",
    "lat": 2.58,
    "lon": -76.5,
    "perpetrator": "EMC (frente Jaime Martinez)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "military",
    "fatalities": 1,
    "injuries": 6,
    "civKilled": 0,
    "milKilled": 1,
    "notes": "fue asesinado el subteniente Ronald Darío Bedoya Rivero y resultaron heridos seis soldados profesionales."
  },
  {
    "id": "COL-2026-038",
    "date": "6/19/2026",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "crossfire ELN / Frente 33",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 1,
    "injuries": 6,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "menor de 13 anos muerto + 5-7 heridos (misma familia); granada impacto vivienda"
  },
  {
    "id": "COL-2026-039",
    "date": "6/19/2026",
    "departamento": "Norte de Santander",
    "municipio": "Tibu",
    "lat": 8.64,
    "lon": -72.74,
    "perpetrator": "EMC (Estructura Criminal 33)",
    "status": "attack",
    "method": "kinetic_drop",
    "target": "civilian",
    "fatalities": 1,
    "injuries": 2,
    "civKilled": 1,
    "milKilled": 0,
    "notes": "Fallecimiento de un niño de 10 años, un bebé de dos años y un joven de 17 resultaron heridos."
  }
];
